config/routes.rb
Rails.application.routes.draw do
  resources :projects
	resources :members
  root to: 'members#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :position, :balance)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :deadline, :client, :price, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ej</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>


	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->


  </head>

<body>
<!--layout-container start-->
<div id="layout-container"> 
  <!--Left navbar start-->
  <div id="nav"> 
    <!--logo start-->
    <div class="profile">
      <div class="logo"><a href="index.html"><img src="images/logo.png" alt=""></a></div>
    </div>
    <!--logo end--> 
    
    <!--navigation start-->
    <ul class="navigation">
      <li><a class="active" href="index.html"><i class="fa fa-home"></i><span>Início</span></a></li>
      <li class="sub"> <a href="#"><i class="fa fa-smile-o"></i><span>UI Elements</span></a>
        <ul class="navigation-sub">
          <li><a href="buttons.html"><i class="fa fa-power-off"></i><span>Button</span></a></li>
          <li><a href="grids.html"><i class="fa fa-columns"></i><span>Grid</span></a></li>
          <li><a href="icons.html"><i class="fa fa-flag"></i><span>Icon</span></a></li>
          <li><a href="tab-accordions.html"><i class="fa fa-plus-square-o"></i><span>Tab / Accordion</span></a></li>
          <li><a href="nestable.html"><i class="fa  fa-arrow-circle-o-down"></i><span>Nestable</span></a></li>
          <li><a href="slider.html"><i class="fa fa-font"></i><span>Slider</span></a></li>
          <li><a href="timeline.html"><i class="fa fa-filter"></i><span>Timeline</span></a></li>
          <li><a href="gallery.html"><i class="fa fa-picture-o"></i><span>Gallery</span></a></li>
        </ul>
      </li>
      <li class="sub"><a href="#"><i class="fa fa-list-alt"></i><span>Forms</span></a>
        <ul class="navigation-sub">
          <li><a href="form-components.html"><i class="fa fa-table"></i><span>Components</span></a></li>
          <li><a href="form-validation.html"><i class="fa fa-leaf"></i><span>Validation</span></a></li>
          <li><a href="form-wizard.html"><i class="fa fa-th"></i><span>Wizard</span></a></li>
          <li><a href="input-mask.html"><i class="fa fa-laptop"></i><span>Input Mask</span></a></li>
          <li><a href="muliti-upload.html"><i class="fa fa-files-o"></i><span>Multi Upload</span></a></li>
        </ul>
      </li>
      <li class="sub"><a href="#"><i class="fa fa-table"></i><span>Table</span></a>
        <ul class="navigation-sub">
          <li><a href="basic-tables.html"><i class="fa fa-table"></i><span>Basic Table</span></a></li>
          <li><a href="data-tables.html"><i class="fa fa-columns"></i><span>Data Table</span></a></li>
        </ul>
      </li>
      <li class="sub"><a href="#"><i class="fa fa fa-envelope"></i><span>Mail</span></a>
        <ul class="navigation-sub">
          <li><a href="mail.html"><i class="fa fa-inbox"></i><span>Inbox</span></a></li>
          <li><a href="mail-compose.html"><i class="fa fa-envelope-o"></i><span>Compose Mail</span></a></li>
        </ul>
      </li>


    </ul>
    <!--navigation end--> 
  </div>
  <!--Left navbar end--> 
  
  <!--main start-->
  <div id="main">
    <div class="head-title">
      <div class="menu-switch"><i class="fa fa-bars"></i></div>
      <!--row start-->
      <div class="row"> 
        <!--col-md-12 start-->
        <div style="position:absolute; color:white; font-size:40px">Coca Jr.</div>
        <div class="col-md-12"> 
          <!--profile dropdown start-->
          <ul class="user-info pull-right fadeInLeftBig animated">

            <li class="profile-info dropdown"> <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <img class="img-circle" alt="" src="images/avatar.jpg">Scott henderson </a>
              <ul class="dropdown-menu">
                <li class="caret"></li>
                <li> <a href="edit-profile.html"> <i class="fa fa-user"></i> Edit Profile </a> </li>
                <li> <a href="mail.html"> <i class="fa fa-inbox"></i> Inbox </a> </li>
                <li> <a href="fullcalendar.html"> <i class="fa fa-calendar"></i> Calendar </a> </li>
                <li> <a href="login.html"> <i class="fa fa-clipboard"></i> Log Out </a> </li>
              </ul>
            </li>
           
          </ul><!--profile dropdown end--> 
          
          <!--top nav start-->
          <ul class="nav top-menu hidden-xs notify-row fadeInRightBig animated">
            <!--task start-->

           
          </ul><!--top nav end--> 
        </div>
        <!--col-md-12 end--> 
      </div>
      <!--row end--> 
    </div>
    <!--margin-container start-->
    <div class="margin-container"> 
      <!--scrollable wrapper start-->
      <div class="scrollable wrapper"> 
       <%= yield %>
        
    
      
        
      </div>
      <!--scrollable wrapper end--> 
    </div>
    <!--margin-container end--> 
  </div>
  <!--main end-->
  <!-- sidebar chats -->

<!-- /sidebar chats -->   
</div>
<!--layout-container end--> 

<%=javascript_include_tag "application"%>
</body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, id: :member_position %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance, id: :member_balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table style="float: left;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.position %></td>
        <td><%= member.balance %></td>
        <td><%= link_to 'Show', member, class: "btn btn-round btn-primarybtn btn-round btn-primarybtn btn-round btn-primary" %></td>
        <td><%= link_to 'Edit', edit_member_path(member), class: "btn btn-round btn-primarybtn btn-round btn-primary" %></td>
        <td><%= link_to 'Destroy', member, class: "btn btn-round btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div style="margin-top: 8%">
<%= link_to 'New Member', new_member_path, class: "btn btn-primary" %>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @member.position %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @member.balance %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline, id: :project_deadline %>
  </div>

  <div class="field">
    <%= form.label :client %>
    <%= form.text_field :client, id: :project_client %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :project_price %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :project_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deadline</th>
      <th>Client</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.deadline %></td>
        <td><%= project.client %></td>
        <td><%= project.price %></td>
        <td><%= project.status %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @project.deadline %>
</p>

<p>
  <strong>Client:</strong>
  <%= @project.client %>
</p>

<p>
  <strong>Price:</strong>
  <%= @project.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>